builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      linux: Linux
      windows: Windows
      darwin: macOS
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge'
      - '^docs:'
      - '^test:'
