apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:

  - name: Prometheus
    type: prometheus
    orgId: 1
    uid: my_prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: 10s